[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I"]
ignore = []
fix = true

[tool.ruff.isort]
known-first-party = ["ris_watcher"]
profile = "black"
